env:
- L10N="-ach -af -an -ar -ast -az -be -bg -bn -br -bs ca -ca-valencia -cak cs -cy -da de -dsb el en-CA en-GB en-US eo es-AR es-CL es-ES -es-MX -et eu fa -ff -fi fr -fur -fy-NL -ga-IE -gd -gl -gn -gu-IN -he -hi-IN -hr -hsb -hu -hy-AM -ia -id -is it ja -ka -kab -kk -km -kn -ko -lij -lt -lv -mk -mr -ms -my -nb-NO -ne-NP -nl -nn-NO -oc -pa-IN -pl -pt-BR -pt-PT -rm -ro -ru -sat -sc -sco -si -sk -skr -sl -son -sq -sr -sv-SE -szl -ta -te -tg -th -tl -tr -trs uk -ur -uz -vi -xh -zh-CN -zh-TW"
prelude:
- |-
  export FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox" && \
  export JOBS={{ ( index .Values.labels "jobs" ) | default "3" }} && \
  eval 'mkdir -p /var/cache/portage/distfiles || true' && \
  chown portage:portage -R /var/cache/portage/ && \
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t && \
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t && \
  {{- end }}
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }} && \
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }} && \
  {{- end }}
  export LUET_PORTAGE_CACHE_PACKAGES="/var/cache/portage/packages" && \
  export LUET_PORTAGE_IGNORE_TAR_WARNING=1 && \
  export LUET_PORTAGE_PKGMETA=1 && \
  export LUET_PORTAGE_PKGFILES=1 && \
  eval 'rm -rf /pkgdir/ || true' && mkdir -p /pkgdir/{{ .Values.name }} && \
  luet-portage --dir /pkgdir/{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }} && \
  eval 'rm -v /var/cache/distfiles/* ${LUET_PORTAGE_CACHE_PACKAGES}/* || true'
package_dir: /pkgdir/{{ .Values.name }}
excludes:
- ^/var/cache/portage/
- ^/var/git/
requires:
- name: macaroni-funtoo-race17
  version: '>=0'
  category: seed
