requires:
  - name: funtoo-stage3
    category: "seed"
    version: ">=0"
env:
- JOBS=10
- GIT_HISTORY_ENTRIES=3000
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- LUET_YES=true
- LUET_NOLOCK=true
prelude:
- >-
  mv kits-versions / &&
  curl https://raw.githubusercontent.com/geaaru/luet/geaaru/contrib/config/get_luet_root.sh | sh &&
  luet install
  repository/mottainai-stable
  repository/geaaru
  system/luet-devkit &&
  luet install --sync-repos
  dev-util/pkgs-checker-minimal utils/yq &&
  luet install system/entities --sync-repos && luet upgrade &&
  luet cleanup &&
  ego sync &&
  cd /var/git/meta-repo/kits &&
  ls -l &&
  for i in $(ls .) ; do
  echo $i ;
  if [ -e /kits-versions/$i.yml ] ; then
  hash=$(yq r /kits-versions/$i.yml 'commit') ;
  echo "For kit $i set hash $hash" ;
  pushd $i ;
  git pull -ff --depth=$GIT_HISTORY_ENTRIES ;
  git checkout $hash || exit 1 ;
  popd ;
  fi ;
  done
- >-
  cp patches/libical-3.0.11.ebuild /var/git/meta-repo/kits/core-kit/dev-libs/libical/ &&
  cd /var/git/meta-repo/kits/core-kit/dev-libs/libical &&
  ebuild libical-3.0.11.ebuild digest
- >-
  cp patches/java/* /var/git/meta-repo/kits/java-kit/ -rfv &&
  cd /var/git/meta-repo/kits/java-kit/dev-java/openjdk-bin/ &&
  ebuild openjdk-bin-11.0.13_p8.ebuild digest &&
  ebuild openjdk-bin-17.0.1_p12.ebuild digest &&
  cd /var/git/meta-repo/kits/java-kit/dev-java/openjdk-jre-bin/ &&
  ebuild openjdk-jre-bin-11.0.11_p9.ebuild digest
- >-
  cp patches/text-kit/* /var/git/meta-repo/kits/text-kit/ -rfv
- >-
  cp -rvf kits-patches/core-kit/* /var/git/meta-repo/kits/core-kit/ &&
  cp -rvf kits-patches/nokit/* /var/git/meta-repo/kits/nokit/ &&
