requires:
  - name: funtoo-stage3
    category: "seed"
    version: ">=0"
env:
- JOBS=10
- GIT_HISTORY_ENTRIES=3000
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- LUET_YES=true
- LUET_NOLOCK=true
prelude:
- >-
  mv kits-versions / &&
  curl https://raw.githubusercontent.com/geaaru/luet/geaaru/contrib/config/get_luet_root.sh | sh &&
  luet install --sync-repos
  system/luet-devkit
  dev-util/pkgs-checker-minimal utils/yq &&
  luet install system/entities --sync-repos && luet upgrade &&
  luet cleanup &&
  ego sync &&
  cd /var/git/meta-repo/kits &&
  chown root:root -R /var/git/meta-repo/kits &&
  ls -l &&
  for i in $(ls .) ; do
  echo $i ;
  if [ -e /kits-versions/$i.yml ] ; then
  hash=$(yq r /kits-versions/$i.yml 'commit') ;
  echo "For kit $i set hash $hash" ;
  pushd $i ;
  git pull -ff --depth=$GIT_HISTORY_ENTRIES ;
  git checkout $hash || exit 1 ;
  popd ;
  fi ;
  done &&
  chown portage:portage -R /var/git/meta-repo/kits

- >-
  cp patches/libical-3.0.11.ebuild
  /var/git/meta-repo/kits/core-kit/dev-libs/libical/ &&
  cd /var/git/meta-repo/kits/core-kit/dev-libs/libical &&
  ebuild libical-3.0.11.ebuild digest

- sh patches4funtoo.sh && sh patches4macaroni.sh
