image: macaronios/phoenix-dev-minimal-devel:latest-amd64
prelude:
- >-
  anise repo update &&
  anise upgrade -y &&
  anise install -y --force
  system/luet-devkit
  app-misc/jq-bin
  app-misc/yq4-bin
  dev-util/pkgs-checker
  app-admin/macaronictl
  app-admin/whip
  app-admin/entities
  sys-apps/whip-catalog
  pinentry make git
  toolchain/base
  toolchain/base-extra
  toolchain/meta-repo
  macaroni/entities-catalog
  qtbase
  gnome-keyring
  kde-frameworks-6/kguiaddons
  kde-frameworks-6/kwindowsystem
  libgpg-error
  libgcrypt
  app-crypt-4/gcr
  app-crypt/gcr
  vala
  libsecret
  efl
  wayland
  eselect-pinentry
  gcc-config &&
  mkdir /tmp/ && chmod a+rwx /tmp &&
  eselect gcc set 1 &&
  eval 'rm /etc/localtime || true' &&
  ln -s /usr/share/zoneinfo/Europe/Rome /etc/localtime &&
  macaronictl env-update &&
  eval 'locale-gen || true' &&
  anise cleanup --purge-repos
steps:
- |-
  export FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox" && \
  export JOBS={{ ( index .Values.labels "jobs" ) | default "3" }} && \
  eval 'mkdir -p /var/cache/portage/distfiles || true' && \
  chown portage:portage -R /var/cache/portage/ && \
  USE="lua caps gnome-keyring gtk qt6 efl wayland X" emerge pinentry -j ${JOBS}
- >-
  export LUET_PORTAGE_CACHE_PACKAGES="/var/cache/portage/packages" &&
  export LUET_PORTAGE_IGNORE_TAR_WARNING=1 &&
  export LUET_PORTAGE_PKGMETA=1 &&
  export LUET_PORTAGE_PKGFILES=1 &&
  eval 'rm -rf /pkgdir/ || true' && mkdir -p /pkgdir/{{ .Values.name }} &&
  luet-portage --dir /pkgdir/{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }} &&
  eval 'rm -v /var/cache/distfiles/* ${LUET_PORTAGE_CACHE_PACKAGES}/* || true'

package_dir: /pkgdir/{{ .Values.name }}
excludes:
- ^/var/cache/portage/
- ^/var/git/
includes:
- /usr$
- /usr/bin$
{{ if eq .Values.name "pinentry-qt" }}
- /usr/bin/pinentry-qt6
- /usr/bin/pinentry-qt
{{ end }}
{{ if eq .Values.name "pinentry-gnome" }}
- /usr/bin/pinentry-gnome3
{{ end }}
{{ if eq .Values.name "pinentry-efl" }}
- /usr/bin/pinentry-efl
{{ end }}
