env:
  - JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
  - LUET_PORTAGE_CACHE_PACKAGES="/var/cache/portage/packages"
  - LUET_PORTAGE_IGNORE_TAR_WARNING=1
  - LUET_PORTAGE_PKGMETA=1
  - LUET_PORTAGE_PKGFILES=1
  - FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
prelude:
  - >-
    wget https://github.com/Sabayon/pkgs-checker/releases/download/v0.10.5/pkgs-checker-v0.10.5-linux-amd64 -O /usr/bin/pkgs-checker && chmod a+x /usr/bin/pkgs-checker
  - eval 'rm -rf /pkgdir/ || true' && mkdir -p /pkgdir/{{ .Values.name }} && luet-portage --dir /pkgdir/{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
  - rm -v /var/cache/distfiles/* ${LUET_PORTAGE_CACHE_PACKAGES}/* || true
package_dir: /pkgdir/{{ .Values.name }}
requires:
  - name: funtoo-base
    version: '>=0'
    category: seed
excludes:
  - ^/var/cache/portage/
  - ^/var/git/
