project_name: Macaroni Eagle
build:
  skip: true
release:
  header: |
    ## Macaroni {{ .Tag }}!

    A new release of Macaroni Eagle is out!

    In evidence:

      * Incus 6.13

      * Python 3.9.22

      * NodeJS 20.19.5, 22.21.0

      * Rust 1.87.0

      * Bind 9.21.12

      * SystemD 254.21

      * PostgreSQL 13.21, 16.9

      * MySQL Community 8.0.42

      * Minio 2025.09.07

      * Strongswan 6.0.2

      * OpenSSH 10.0_p2

      * OpenSSL 1.1.1w

      * OpenVPN 2.6.14

      * Wireguard Tools 1.0.20250521

      * Backrest 1.9.2

      * Cryptography 46.0.2

      * Redis 7.4.4

      * Github Cli 2.74.0

      * CoreDNS 1.13.1

      * Caddy 2.10.2

    Security fixes:
    * CVE-2024-12797 (Cryptography 42.0.8)
    * CVE-2025-50181 (urlib3 1.26.20)
    * CVE-2024-47081 (requests 2.32.3)
    * CVE-2025-58185 (Go 1.24.6)
    * CVE-2025-58188 (Go 1.24.6)
    * CVE-2025-61723 (Go 1.24.6)
    * CVE-2025-61725 (Go 1.24.6)
    * CVE-2025-58189 (Go 1.24.6)
    * CVE-2025-47912 (Go 1.24.6)
    * CVE-2025-58186 (Go 1.24.6)
    * CVE-2025-61724 (Go 1.24.6)
    * CVE-2025-47273 (Setuptools 70.3.0)

    See the above list for all upgrade details.

    Many thanks to all Macaroni OS devs and contributors that are the sap of all this.

    Enjoy!

    Any user that wants to support our work for Macaroni could do this through the Github [Sponsor](https://github.com/sponsors/geaaru) or [Liberapay](https://liberapay.com/geaaru/).

changelog:
  sort: asc
  groups:
    - title: New packages
      regexp: ".*new.*"
      order: 1
    - title: Reverts
      regexp: '.*Revert.*'
      order: 3
    - title: Packages
      regexp: ".*Bump.*"
      order: 2
    - title: Others
      order: 9999
  filters:
    exclude:
      - '^.github'
      - '^github'
      - '^portage-converter'
      - '^.gorelease'
