project_name: Macaroni Eagle
build:
  skip: true
release:
  header: |
    ## Macaroni {{ .Tag }}!

    A new release of Macaroni Eagle is out!

    Macaroni Terragon tree now use the new *mark-devkit* tool to setup the kits.

    In evidence:

      * Incus 6.8

      * Prometheus 3.1.0

      * Python 3.9.21

      * PHP 8.2.27

      * NodeJS 20.18.2

      * Rust 1.84.0

      * Git 2.48.1

      * Bind 9.20.4

      * SystemD 254.21

      * Grafana 11.4.0

      * PostgreSQL 13.18, 14.15, 16.6

      * MySQL Community 8.0.41

      * Minio 2025.01.20

      * HaProxy 2.6.13

      * Strongswan 6.0.0

    See the above list for all upgrade details.

    Many thanks to all Macaroni OS devs and contributors that are the sap of all this.

    Enjoy!

    Any user that wants to support our work for Macaroni could do this
    through the Github [Sponsor](https://github.com/sponsors/geaaru).

changelog:
  sort: asc
  groups:
    - title: New packages
      regexp: ".*new.*"
      order: 1
    - title: Reverts
      regexp: '.*Revert.*'
      order: 3
    - title: Packages
      regexp: ".*Bump.*"
      order: 2
    - title: Others
      order: 9999
  filters:
    exclude:
      - '^.github'
      - '^github'
      - '^portage-converter'
      - '^.gorelease'
