project_name: Macaroni Eagle
build:
  skip: true
release:
  header: |
    ## Macaroni {{ .Tag }}!

    A new release of Macaroni Eagle is out!

    This release migrate to OpenSSL 3.0!

    In evidence:

      * Go 1.24.13, 1.25.11, 1.26.4

      * NodeJS 20.20.2, 22.22.2

      * Bind 9.21.21

      * Strongswan 6.0.5

      * OpenVPN 2.7.1

      * Tor 0.4.9.8

      * Wireguard Tools 1.0.20260223

      * Coreutils 9.11

      * DBus 1.16.2

      * Upx (Upstream) 5.2.0

      * Docker 29.4.3

      * LXC 6.0.6

      * LXD 6.7

      * QEmu 10.2.2

      * Incus 6.23.0

      * Alert Manager (Upstream) 0.32.1

      * MySQL Community 8.0.45

      * Python 3.9.25

      * Rust 1.94.1

      * Erlang 28.5.0.2

      * Zig (Upstream) 0.16.0

      * OpenSSL 3.0.19

      * Cryptography 46.0.7

      * Setuptools 80.10.2

      * CMake 3.31.10

      * Meson 1.8.5

      * Ninja 1.13.2

      * CoreDNS 1.14.2

      * Iptables 1.8.13

      * Nftables 1.1.6

      * Minio 2026.06.18

      * Rclone 1.74.1

      * Shadow 4.19.4

      * Caddy 2.11.3

      * Grafana (Upstream) 13.0.1

      * Backrest 1.13.0

      * Prometheus 3.12.0

    See the above list for all upgrade details.

    Many thanks to all Macaroni OS devs and contributors that are the sap of all this.

    Enjoy!

    Any user that wants to support our work for Macaroni could do this through the Github [Sponsor](https://github.com/sponsors/geaaru) or [Liberapay](https://liberapay.com/geaaru/).

changelog:
  sort: asc
  groups:
    - title: New packages
      regexp: ".*new.*"
      order: 1
    - title: Reverts
      regexp: '.*Revert.*'
      order: 3
    - title: Packages
      regexp: ".*Bump.*"
      order: 2
    - title: Others
      order: 9999
  filters:
    exclude:
      - '^.github'
      - '^github'
      - '^portage-converter'
      - '^.gorelease'
