FROM alpine
RUN mkdir /phoenix-minimal/etc/ /phoenix-minimal/etc/anise -p
ADD conf/anise.yaml.docker.devel /phoenix-minimal/etc/anise/anise.yaml
FROM macaronios/anise:latest-amd64

COPY --from=0 /phoenix-minimal/ /
ENV USER=root

RUN [ \
  "/usr/bin/anise", "install", "-y", "--force", "--sync-repos", \
  "--cleanup", "--purge-repos", "--config", "/etc/anise/anise.yaml", \
  "repository/mark", \
  "repository/macaroni-commons", \
  "repository/macaroni-phoenix"]

RUN [ \
  "/usr/bin/anise", "install", "-y", "--force", "--sync-repos", \
  "--purge-repos", "--config", "/etc/anise/anise.yaml", \
  "--skip-config-protect", "--cleanup", \
  "app-admin/entities", \
  "app-admin/anise", \
  "sys-apps/shadow", \
  "sys-apps/sed", \
  "app-shells/bash", \
  "glibc", \
  "gcc", \
  "sys-apps/iproute2", \
  "sysvinit", \
  "sys-apps/coreutils", \
  "sys-apps/openrc", \
  "virtual/base", \
  "virtual-entities/base", \
  "app-admin/macaronictl-thin" ]

SHELL ["/bin/bash", "-c"]

RUN macaronictl env-update && \
  anise rm -y --nodeps virtual-entities/base && \
  anise cleanup --purge-repos

ENV TMPDIR=/tmp
ENTRYPOINT ["/bin/bash"]
