FROM alpine
RUN mkdir /funtoo-minimal/etc/ -p

FROM macaronios/anise:latest-amd64
ADD conf/anise.yaml.docker /etc/anise/anise.yaml
COPY --from=0 /funtoo-minimal/ /
ENV USER=root

RUN [ \
  "/usr/bin/anise", "install", "-y", "--force", "--sync-repos", \
  "--cleanup", "--purge-repos", \
  "repository/mottainai-stable", \
  "repository/macaroni-commons-testing", \
  "repository/macaroni-eagle-legacy"]

RUN [ \
  "/usr/bin/anise", "install", "-y", "--force", "--sync-repos", \
  "--cleanup", "--purge-repos", \
  "--skip-config-protect", \
  "app-admin/entities", \
  "app-admin/anise", \
  "sys-apps/shadow", \
  "sys-apps/sed", \
  "app-shells/bash", \
  "gcc", "glibc", \
  "sys-libs/ncurses", \
  "sys-apps/systemd", \
  "sys-apps/coreutils", \
  "sys-apps/iproute2", \
  "virtual/base", \
  "virtual-entities/base", \
  "app-admin/macaronictl-thin" ]

SHELL ["/bin/bash", "-c"]

RUN macaronictl env-update && \
  anise rm -y --nodeps virtual-entities/base macaroni/entities-catalog && \
  anise cleanup --purge-repos

ENV TMPDIR=/tmp
ENTRYPOINT ["/bin/bash"]
