FROM alpine
RUN mkdir /funtoo-minimal/etc/ -p
FROM macaronios/luet:latest-amd64
ADD conf/luet.yaml.docker.devel /etc/luet/luet.yaml

COPY --from=0 /funtoo-minimal/ /
ENV USER=root

RUN [ \
  "/usr/bin/luet", "install", "-y", "--force", "--sync-repos", \
  "--purge-repos", \
  "repository/mottainai-dev", \
  "repository/macaroni-commons-dev", \
  "repository/macaroni-phoenix-dev"]

RUN [ \
  "/usr/bin/luet", "install", "-y", "--force", "--sync-repos", \
  "--purge-repos", \
  "--skip-config-protect", \
  "system/entities", \
  "system/luet-geaaru-testing", \
  "sys-apps/shadow", \
  "sys-apps/sed", \
  "app-shells/bash", \
  "glibc", \
  "gcc", \
  "sys-apps/iproute2", \
  "sysvinit", \
  "sys-apps/coreutils", \
  "sys-apps/openrc", \
  "virtual/base", \
  "virtual-entities/base", \
  "app-admin/macaronictl-thin" ]

SHELL ["/bin/bash", "-c"]

RUN macaronictl env-update && \
  luet rm -y --nodeps virtual-entities/base && \
  luet cleanup --purge-repos

ENV TMPDIR=/tmp
ENTRYPOINT ["/bin/bash"]
