# Macaroni OS Dracut Default parameters

dracutmodules="rescue resume bash kernel-modules rootfs-block udev-rules usrmount base fs-lib shutdown  terminfo btrfs  plymouth lvm shutdown crypt lvm mdraid crypt"

omit_dracutmodules="fcoe"

# Needed for handle correctly encrypted partition with luks
# With dracut-059 we need spaces before and later to avoid errors.
add_drivers+=" dm_mod dm_crypt "

# Quiet messages: failed to execute '/usr/lib/elogind/elogind-uaccess-command' '/usr/lib/elogind/elogind-uaccess-command /dev/dri/card0 ': No such file or directory
install_items+=" /usr/lib/elogind/elogind /usr/lib/elogind/elogind-cgroups-agent /usr/lib/elogind/elogind-uaccess-command /usr/lib/elogind/elogind-userdbd /usr/lib/elogind/elogind-userwork "
