requires:
  - name: mark-kits
    category: "seed"
    version: ">=0"
env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
package_dir: /{{ .Values.name }}
steps:
# It seems that the i18n-kit is without the python-kit profile.
# I need to investigate on this.
- >-
  sed -i -e '/i18n/d' /etc/portage/make.profile/parent &&
  mkdir -p /{{ .Values.name }}/var/git/ &&
  cp -rvf /var/git/meta-repo/ /{{ .Values.name }}/var/git/ &&
  mkdir -p /{{ .Values.name }}/etc/portage/repos.conf/ &&
  mkdir -p /{{ .Values.name }}/etc/portage/make.profile/ &&
  cp -rvf /etc/portage/repos.conf/* /{{ .Values.name }}/etc/portage/repos.conf/ &&
  cp -rvf /etc/portage/make.profile/* /{{ .Values.name }}/etc/portage/make.profile/ &&
  eval 'rm /{{ .Values.name }}/etc/portage/repos.conf/geaaru-kit || true'

