requires:
- category: "seed"
  name: "funtoo-boot"
  version: ">=0"
env:
- JOBS=3
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
prelude:
- >-
  cp -rvf package.use/* /etc/portage/package.use/ &&
  emerge -t -j $JOBS {{ ( index .Values.labels "emerge.packages" ) }} &&
  rm -rf /var/cache/portage/distfiles/*
