requires:
  - name: "kernel-zen"
    category: "seed-6.7"
    version: ">=0"
env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
package_dir: /{{ .Values.name }}
steps:
- >-
  luet i -y sys-apps/kmod virtual/modutils pkgconf virtual/libelf
  virtual/linux-sources && luet cleanup
- >-
  sed -i -e 's|^ZFS_KERNEL_COMPAT.*|ZFS_KERNEL_COMPAT="6.7"|g' /var/git/meta-repo/kits/core-kit/sys-fs/zfs-kmod/zfs-kmod-2.2.3.ebuild
- >-
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  eval 'rm -rf /{{ .Values.name }} || true' && mkdir /{{ .Values.name }} && \
  luet-portage --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}

# It seems that the compression is not handled correct from the ebuild
# I run manually compression for every module
- >-
  for i in $(find /{{ .Values.name }}/lib/modules/{{ ( index .Values.labels "kernel.version" ) }}-macaroni/extra/ -name '*.ko') ; do
  zstd ${i} -o ${i}.zst --rm ;
  done

excludes:
# Funtoo/Portage stuff
- ^/var/db/pkg/
- ^/var/cache/portage/
- ^/var/git/

# Exclude file that conflict between different versions
- ^/usr/share/doc/.*
- ^/usr/src/.*
