env:
  - JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
  - LUET_PORTAGE_CACHE_PACKAGES="/var/cache/portage/packages"
  - LUET_PORTAGE_IGNORE_TAR_WARNING=1
  - LUET_PORTAGE_PKGMETA=1
  - LUET_PORTAGE_PKGFILES=1
  - FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
prelude:
  - eval 'rm -rf /pkgdir/ || true' && mkdir -p /pkgdir/{{ .Values.name }} && luet-portage --dir /pkgdir/{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
  - rm -v /var/cache/distfiles/* ${LUET_PORTAGE_CACHE_PACKAGES}/* || true
# Add support to dhclient until will be integrated directly
  - >-
    mkdir -p /pkgdir/{{ .Values.name }}/etc/conf.d/ &&
    cp dhclient-netif /pkgdir/{{ .Values.name }}/etc/netif.d/dhclient &&
    cp dhclient-conf.d /pkgdir/{{ .Values.name }}/etc/conf.d/dhclient
package_dir: /pkgdir/{{ .Values.name }}
requires:
  - name: funtoo-base
    version: '>=0'
    category: seed
excludes:
  - ^/var/cache/portage/
  - ^/var/git/
