env:
- LUET_YES=true
- LUET_NOLOCK=true
- KERNEL_VERSION={{ ( index .Values.labels "kernel.version" ) }}
prelude:
# dev-util/kbuild is needed for virtualbox-guest-additions
- >-
  anise repo update &&
  anise upgrade &&
  anise install --sync-repos
  kernel-6.12/macaroni-sources
  kernel-6.12/macaroni-modules
  kernel-6.12/macaroni-full
  dev-util/kbuild kmod
  &&
  anise cleanup --purge-repos &&
  cd /usr/src && eval 'rm linux || true' &&
  ln -s linux-$KERNEL_VERSION-macaroni linux
requires:
- category: "seed"
  name: "macaroni-funtoo-base"
  version: ">=0"
