requires:
- category: "seed"
  name: "funtoo-kit-geaaru"
  version: ">=0"
env:
- JOBS=10
- GENTOO_MIRRORS=https://direct.funtoo.org
prelude:
- >-
  cp -rvf package.use /etc/portage/ &&
  cp -v make.conf /etc/portage &&
  cp -rvf patches /etc/portage/ &&
  epro flavor minimal &&
  epro mix-in +btrfs +vmware-guest &&
  epro list
- luet upgrade --sync-repos &&
  luet i repository/macaroni-commons-dev &&
  luet i --force --sync-repos macaroni/entities-catalog
  system/entities &&
  luet cleanup --purge-repos &&
  rm -rf /etc/passwd /etc/group /etc/passwd /etc/shadow &&
  entities merge -s /usr/share/macaroni/entities -a &&
  entities list users &&
  entities list groups
#steps:
# Tempory patch for iproute2
- >-
  sed '/-5.12.0-configure-nomagic.patch/d'  /var/git/meta-repo/kits/core-kit/sys-apps/iproute2/iproute2-6.7.0.ebuild  -i
- >-
  emerge --unmerge
  sys-fs/lvm2
  virtual/udev
  virtual/libudev
  virtual/dev-manager
  virtual/service-manager
  sys-apps/gentoo-systemd-integration
  sys-apps/sysvinit
  sys-fs/eudev
  net-dns/openresolv
  sys-apps/corenetwork
  sys-apps/opentmpfiles
  virtual/udev
  virtual/tmpfiles
  sys-apps/openrc
  net-misc/dhcpcd
  sys-apps/usbutils
  sys-apps/pciutils
  sys-fs/dosfstools
  &&
  export FEATURES="-collision-protect -sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox" &&
  emerge -1 -t -j $JOBS sys-apps/systemd &&
  emerge -1uDN -t -j $JOBS @system &&
  emerge -t -j $JOBS -D @world &&
  emerge -t -j $JOBS net-misc/curl dev-util/cmake dev-python/zipp &&
  rm -rf /var/cache/portage/distfiles/*
