requires:
- category: "seed"
  name: "funtoo-kit-geaaru"
  version: ">=0"
env:
- JOBS=10
- GENTOO_MIRRORS=https://direct.funtoo.org
prelude:
- >-
  cp -rvf package.use /etc/portage/ &&
  epro mix-ins
  +kde-plasma-5
  +gfxcard-intel-classic
  +gfxcard-nouveau
  +gfxcard-nvidia
  +gfxcard-amdgpu
  +gfxcard-radeon
  +gfxcard-vmware
  +mediaformat-audio-extra
  +mediaformat-gfx-extra
  +mediaformat-video-extra
  +mediadevice-video-pro
  +vmware-guest &&
  emerge --unmerge x11-libs/amtk
- >-
  export LUET_YES=true &&
  export LUET_NOLOCK=true &&
  export LUET_VERSION={{ ( index .Values.labels "luet_version" ) }} &&
  wget https://github.com/geaaru/luet/releases/download/v${LUET_VERSION}-geaaru/luet-v${LUET_VERSION}-geaaru-Linux-x86_64 -O /usr/bin/luet &&
  chmod a+x /usr/bin/luet &&
  luet upgrade --sync-repos  &&
  luet install repository/macaroni-commons  &&
  luet install --force --sync-repos
  macaroni/entities-catalog
  system/entities
  system/luet-geaaru &&
  luet cleanup --purge-repos &&
  rm -rf /etc/passwd /etc/group /etc/passwd /etc/shadow &&
  entities merge -s /usr/share/macaroni/entities -a &&
  entities list users &&
  entities list groups

# Temporary workaround
- >-
  cp patches/noto-20220613.ebuild 
  /var/git/meta-repo/kits/media-kit/media-fonts/noto/noto-20220613.ebuild &&
  cd /var/git/meta-repo/kits/media-kit/media-fonts/noto &&
  rm Manifest &&
  ebuild /var/git/meta-repo/kits/media-kit/media-fonts/noto/noto-20220613.ebuild digest

- >-
  cp -rvf patches/babl/files /var/git/meta-repo/kits/gnome-kit/media-libs/babl/ &&
  cp patches/babl/babl-0.1.78.ebuild /var/git/meta-repo/kits/gnome-kit/media-libs/babl/babl-0.1.78.ebuild

- >-
  wget -O /var/git/meta-repo/kits/core-gl-kit/media-libs/mesa/mesa-20.2.4-r2.ebuild
  https://raw.githubusercontent.com/funtoo/core-gl-kit/next/media-libs/mesa/mesa-20.2.4-r2.ebuild &&
  cd /var/git/meta-repo/kits/core-gl-kit/media-libs/mesa/ &&
  rm Manifest &&
  ebuild mesa-20.2.4-r2.ebuild digest && cd -

- >-
  cp -rvf patches/gedit/files /var/git/meta-repo/kits/gnome-kit/app-editors/gedit/ &&
  cp patches/gedit/gedit-3.36.2.ebuild /var/git/meta-repo/kits/gnome-kit/app-editors/gedit/gedit-3.36.2.ebuild

- >-
  export FEATURES="-collision-protect -sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox" &&
  emerge -j $JOBS @world -D --with-bdeps y  -pv -t -e &&
  emerge -t -j $JOBS -DN @world &&
  emerge -t -j $JOBS -D @world &&
  rm -rf /var/cache/portage/distfiles/*
