requires:
- category: "seed"
  name: "funtoo-kit-geaaru"
  version: ">=0"
env:
- JOBS=10
- GENTOO_MIRRORS=https://direct.funtoo.org
- PYTHON_TARGETS="python3_9"
- PYTHON_SINGLE_TARGET="python3_9"
prelude:
- >-
  cp -rvf package.use /etc/portage/ &&
  echo 'CHOST="{{ ( index .Values.labels "arch" ) }}-pc-linux-gnu"' > /etc/portage/make.conf &&
  epro flavor core &&
  epro mix-in +btrfs +vmware-guest &&
  epro list &&
  echo "UTC" > /etc/timezone
- >-
  luet upgrade --sync-repos &&
  luet i repository/macaroni-commons-dev &&
  luet i --force --sync-repos macaroni/entities-catalog
  system/entities &&
  luet cleanup --purge-repos &&
  rm -rf /etc/passwd /etc/group /etc/passwd /etc/shadow &&
  entities merge -s /usr/share/macaroni/entities -a &&
  entities list users &&
  entities list groups &&
  export FEATURES="-collision-protect -sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox" &&
  unset RELEASE &&
  emerge --unmerge sys-kernel/debian-sources x11-drivers/nvidia-kernel-modules app-emulation/open-vm-tools &&
  emerge -j $JOBS @world -D --with-bdeps y -t -e &&
  emerge -t -j $JOBS -DN @world &&
  emerge -t -j $JOBS -D @world &&
  emerge -t -j $JOBS -uDN @world &&
  rm -rf /var/cache/portage/distfiles/*
