package_dir: /pkgdir/{{ .Values.name | replace "-portage" "" }}
includes:
  - ^/var/db/pkg
  - ^/var/db$
  - ^/var$
requires:
  - name: font-bh-75dpi
    version: '{{ .Values.version }}'
    category: media-fonts
