requires:
  - name: funtoo-metatools
    category: "layer"
    version: ">=0"
package_dir: /funtoo-metatools
includes:
# NOTE: avoid to add final slash because else the directory /var/db/pkg is not matched
#       and then all files will be removed. You need to define also the parent directory.
- ^/var/db/pkg
- ^/var/db$
- ^/var$
