requires:
  - name: mark-stage3
    category: "seed"
    version: ">=0"
env:
- JOBS=10
- GIT_HISTORY_ENTRIES=30000
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- LUET_YES=true
- LUET_NOLOCK=true
prelude:
- >-
  mv kits-versions / &&
  curl https://raw.githubusercontent.com/macaroni-os/anise/macaroni/contrib/config/get_luet_root.sh | sh &&
  anise subsets enable portage devel &&
  anise repo list &&
  anise repo disable mottainai-stable macaroni-terragon macaroni-commons &&
  anise i --sync-repos repository/mark-dev repository/macaroni-commons-dev repository/macaroni-phoenix-dev &&
  anise install --sync-repos
  dev-util/pkgs-checker app-misc/yq-go app-misc/jq system/luet-devkit
  mark-devkit app-admin/anise-portage-converter app-admin/entities --sync-repos &&
  anise upgrade &&
  anise cleanup &&
  ego sync &&
  cd /var/git/meta-repo/kits &&
  chown root:root -R /var/git/meta-repo/kits &&
  rm -rf * &&
  mark-devkit kit clone --specfile /kits-versions/kits.yaml
  --to /var/git/meta-repo/kits --deep $GIT_HISTORY_ENTRIES
  --concurrency $JOBS
  --generate-reposcan-files --kit-cache-dir /kit-cache/ &&
  cp /kits-versions/kits.yaml /kit-cache/

- >-
  cp patches/libical-3.0.11.ebuild
  /var/git/meta-repo/kits/gnome-kit/dev-libs/libical/ &&
  cd /var/git/meta-repo/kits/gnome-kit/dev-libs/libical &&
  ebuild libical-3.0.11.ebuild digest

- sh patches4funtoo.sh && sh patches4macaroni.sh
