requires:
- category: "seed"
  name: "funtoo-office"
  version: ">=0"
env:
- JOBS=3
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- QEMU_SOFTMMU_TARGETS="i386 x86_64 arm aarch64 mips mips64 mipsel"
- QEMU_USER_TARGETS="i386 x86_64 aarch64 arm mips mips64 mipsel armeb"
prelude:
- >-
  eval 'mkdir -p /etc/portage/package.license/ || true' &&
  eval 'mkdir -p /etc/portage/package.use/ || true' &&
  cp -rvf package.license/* /etc/portage/package.license/ &&
  cp -rvf package.use/* /etc/portage/package.use/ &&
  emerge -t -j $JOBS {{ ( index .Values.labels "emerge.packages" ) }} &&
  rm -rf /var/cache/portage/distfiles/*
