requires:
- category: "seed"
  name: "funtoo-kits"
  version: ">=0"
env:
- FEATURES="-collision-protect -sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
package_dir: /{{ .Values.name }}
prelude:
- >-
  cp geaaru-kit /etc/portage/repos.conf/ &&
  eval 'emerge --sync || true' &&
  cd /var/git/extra-kits/geaaru-kit &&
  git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*' &&
  git fetch --depth 100 &&
  git log -n 3 &&
  git checkout {{ ( index .Values.labels "repo_branch" ) }} &&
  git checkout {{ ( index .Values.labels "repo_hash" ) }} &&
  mkdir /{{ .Values.name }}
