env:
- LUET_YES=true
- LUET_NOLOCK=true
- KERNEL_VERSION={{ ( index .Values.labels "kernel.version" ) }}
prelude:
# dev-util/kbuild is needed for virtualbox-guest-additions
- >-
  luet repo update && luet upgrade &&
  luet install --sync-repos
  kernel-5.10/macaroni-lts-sources kernel-5.10/macaroni-modules
  dev-util/kbuild
  &&
  luet cleanup &&
  cd /usr/src && eval 'rm linux || true' &&
  ln -s linux-$KERNEL_VERSION-macaroni linux
requires:
- category: "seed"
  name: "macaroni-funtoo-base"
  version: ">=0"
