skipped_resolutions:
  packages:
    - name: elt-patches
      category: app-portage

    - name: binutils-apple
      category: sys-devel

    - name: gcc-apple
      category: sys-devel

    # Until conflicts detection is fixed.
    - name: radiusclient-ng
      category: net-dialup

    - name: systemd-tmpfiles
      category: sys-apps

    - name: argp-standalone
      category: sys-libs

    # This package is managed manually.
    - name: nvidia-kernel-modules
      category: x11-drivers

    - name: debian-sources
      category: sys-kernel

    - name: debian-sources-lts
      category: sys-kernel

    - name: vanilla-sources
      category: sys-kernel

    - name: ck-sources
      category: sys-kernel

    - name: gentoo-sources
      category: sys-kernel

    - name: pf-sources
      category: sys-kernel

    - name: xbox-sources
      category: sys-kernel

    - name: mips-sources
      category: sys-kernel

    - name: git-sources
      category: sys-kernel

    - name: aufs-sources
      category: sys-kernel
    - name: cdrtools
      category: virtual

    # Force OR condition for app-text/xmlto
    # on use virtual/w3m
    - name: lynx
      category: www-client
    - name: elinks
      category: www-client

    - name: pkgcore
      category: sys-apps

    # virtual/source is managed by kernel.yaml
    - name: linux-sources
      category: virtual

    - name: jack-audio-connection-kit
      category: media-sound

include_files:
  - ./artefacts/base.yml
  - ./artefacts/base-kde.yml

build_template_file: ../templates/build-pkg-from-layer.yaml.tmpl
build_portage_template_file: ../templates/build-pkg-portage.yaml.tmpl

global_annotations:
  subsets:
    rules:
      devel:
        - "^/usr/include/"
      portage:
        - "^/var/db/pkg/"

artefacts:

- tree: packages/atoms/base
  mutations:
    buildtime_deps:
      packages:
        - category: seed
          name: funtoo-base
  uses:
    disabled:
    - nios2
    - sh
    enabled:
    - udev
  packages:
  - virtual/libusb:1

- tree: packages/atoms/base
  packages:
  - x11-misc/compose-tables

# Artefacts manually changed
- tree: packages/atoms/base
  uses:
    disabled:
    - doc
    - nios2
    - sh
    - static-libs
  packages:
    - dev-libs/iniparser:0

- tree: packages/atoms/base
  mutations:
    buildtime_deps:
      packages:
        - category: seed
          name: funtoo-base
  uses:
    disabled:
    - nios2
    - python_targets_python3_8
    - python_targets_python3_9
    - python_targets_pypy3
    - sh
    enabled:
    - python_targets_python2_7
    - python_targets_python3_7
  packages:
  - dev-lang/python-exec:2

- tree: packages/atoms/base
  replacements:
    buildtime_deps:
      ignore:
        - category: sys-fs
          name: lvm2
  uses:
    disabled:
      - btrfs
      - ibm
      - cryptsetup
      - selinux
  packages:
  - sys-kernel/genkernel

- tree: packages/atoms/base
  mutations:
    buildtime_deps:
      packages:
        - category: seed
          name: funtoo-base
  uses:
    disabled:
    - clippy
    - doc
    - nios2
    - rls
    - rustfmt
    - sh
    enabled:
    - cpu_flags_x86_sse2
  packages:
  - dev-lang/rust-bin:stable

- tree: packages/atoms/base
  ignore_build_deps: true
  mutations:
    buildtime_deps:
      packages:
        - category: seed
          name: funtoo-base
  uses:
    disabled:
    - nios2
    - sh
  packages:
  - virtual/dev-manager
  - virtual/editor
  - virtual/libc
  - virtual/libelf
  - virtual/libffi
  - virtual/libiconv
  - virtual/libintl
  - virtual/man
  - virtual/modutils
  - virtual/os-headers
  - virtual/package-manager
  - virtual/pager
  - virtual/pam
  - virtual/perl-CPAN-Meta
  - virtual/perl-CPAN-Meta-YAML
  - virtual/perl-Carp
  - virtual/perl-Data-Dumper
  - virtual/perl-Digest-MD5
  - virtual/perl-Digest-SHA
  - virtual/perl-Encode
  - virtual/perl-Exporter
  - virtual/perl-ExtUtils-CBuilder
  - virtual/perl-ExtUtils-Install
  - virtual/perl-ExtUtils-MakeMaker
  - virtual/perl-ExtUtils-Manifest
  - virtual/perl-ExtUtils-ParseXS
  - virtual/perl-File-Spec
  - virtual/perl-File-Temp
  - virtual/perl-Getopt-Long
  - virtual/perl-IO
  - virtual/perl-IO-Socket-IP
  - virtual/perl-JSON-PP
  - virtual/perl-MIME-Base64
  - virtual/perl-Module-Metadata
  - virtual/perl-Parse-CPAN-Meta
  - virtual/perl-Perl-OSType
  - virtual/perl-Pod-Parser
  - virtual/perl-Scalar-List-Utils
  - virtual/perl-Test-Harness
  - virtual/perl-Text-ParseWords
  - virtual/perl-podlators
  - virtual/perl-version
  - virtual/pkgconfig
  - virtual/rust
  - virtual/shadow
  - virtual/w3m

- tree: packages/atoms/base
  ignore_build_deps: true
  mutations:
    buildtime_deps:
      packages:
        - category: seed
          name: funtoo-base
  uses:
    disabled:
    - nios2
    - sh
  finalizer:
    install:
    - >-
      if [ ! -e /usr/bin/yacc ] ; then
      cd /usr/bin ;
      ln -s yacc.bison yacc ;
      fi
    shell:
      - bash
      - -c
  packages:
  - virtual/yacc

- tree: packages/atoms/base
  ignore_build_deps: true
  mutations:
    buildtime_deps:
      packages:
        - category: seed
          name: funtoo-base
  uses:
    disabled:
    - nios2
    - sh
  packages:
  - virtual/libintl

- tree: packages/atoms/base
  ignore_build_deps: true
  mutations:
    buildtime_deps:
      packages:
        - category: seed
          name: funtoo-base
  uses:
    disabled:
    - nios2
    - sh
  packages:
  - virtual/service-manager
  - virtual/tmpfiles

- tree: packages/atoms/base
  mutations:
    buildtime_deps:
      packages:
        - category: seed
          name: funtoo-base
  uses:
    disabled:
    - debug
    - doc
    - examples
    - nios2
    - sh
    - static-libs
    - test
    - udev
  packages:
  - dev-libs/libusb:1

- tree: packages/atoms/base
  ignore_build_deps: true
  mutations:
    buildtime_deps:
      packages:
        - category: seed
          name: funtoo-base
  uses:
    disabled:
    - debug
    - doc
    - emacs
    - nios2
    - python_single_target_python3_8
    - python_single_target_python3_9
    - python_targets_python3_8
    - python_targets_python3_9
    - sh
    enabled:
    - python_single_target_python3_7
    - python_targets_python3_7
  packages:
  - dev-util/gtk-doc

- tree: packages/atoms/base
  mutations:
    provides:
      - category: gui-libs-5
        name: amtk
  uses:
    disabled:
    - nios2
    - sh
    - test
    - valgrind
  packages:
  - x11-libs/amtk

include_layers:
- layers/funtoo-base.yaml


# Define the list of the files generated by Funtoo reposcan tool.
reposcan_sources:
#  - source1.json
  - ./kit_cache/browser-kit-1.4-release
  - ./kit_cache/core-gl-kit-2.0-release
  - ./kit_cache/core-hw-kit-1.4-release
  - ./kit_cache/core-kit-1.4-release
  - ./kit_cache/core-server-kit-1.4-release
  - ./kit_cache/desktop-kit-1.4-release
  - ./kit_cache/dev-kit-1.4-release
  - ./kit_cache/editors-kit-1.4-release
  - ./kit_cache/games-kit-1.4-release
  - ./kit_cache/gnome-kit-3.36-prime
  - ./kit_cache/haskell-kit-1.4-release
  - ./kit_cache/java-kit-1.4-release
  - ./kit_cache/kde-kit-5.20-release
  - ./kit_cache/lang-kit-1.4-release
  - ./kit_cache/lisp-scheme-kit-1.4-release
  - ./kit_cache/llvm-kit-1.4-release
  - ./kit_cache/mate-kit-1.24-prime
  - ./kit_cache/media-kit-1.4-release
  - ./kit_cache/ml-lang-kit-1.4-release
  - ./kit_cache/net-kit-1.4-release
  - ./kit_cache/nokit-1.4-release
  - ./kit_cache/perl-kit-5.32-release
  - ./kit_cache/python-kit-3.7-release
  - ./kit_cache/python-modules-kit-1.4-release
  - ./kit_cache/qt-kit-5.15.2-release
  - ./kit_cache/ruby-kit-2.7-prime
  - ./kit_cache/science-kit-1.4-release
  - ./kit_cache/security-kit-1.4-release
  - ./kit_cache/text-kit-1.4-release
  - ./kit_cache/xfce-kit-4.16-release
  - ./kit_cache/geaaru-kit-funtoo

# Disable use of category with slot as requires. Default is without slot.
reposcan_requires_slot: true

reposcan_contraints:
  packages:
    - dev-lang/python:3.7
    - dev-lang/python:2.7
    - dev-lang/ruby:2.6
    - dev-lang/ruby:2.7
    - sys-devel/gcc:9.2.0
    - sys-devel/llvm:11
    - sys-devel/clang:11
    - dev-cpp/gtkmm:3.0
    - app-text/docbook-sgml-dtd:4.4
    - app-text/docbook-sgml-dtd:4.2
    - app-text/docbook-sgml-dtd:4.1
    - app-text/docbook-sgml-dtd:4.0
    - app-text/docbook-sgml-dtd:3.1
    - app-text/docbook-sgml-dtd:3.0
    - dev-cpp/cairomm:0
    - dev-cpp/cairomm:1
    - dev-libs/iniparser:0
    # To fix on geaaru-overlay
    - <x11-libs/libX11-9999
    - <sys-apps/corenetwork-1.7.0


reposcan_disabled_use_flags:
  # !!internal use only!! used for creating build images and the first half of bootstrapping [make stage1]
  - build

  - emacs
  - doc
  - doctool
  - elibc_Cygwin
  - elibc_Darwin
  - elibc_FreeBSD
  - elibc_OpenBSD
  - elibc_NetBSD
  - elibc_SunOS
  - elibc_musl
  - elibc_mingw
  - elibc_uclibc
  - elogind
  - libressl
  - gtk-doc
  - gles2-only
  - python_single_target_python3_6
  - python_single_target_python3_9
  - python_single_target_python3_8
  - python_single_target_python3_10
  # I disable pypy support atm
  - python_single_target_pypy3
  - python_targets_python3_6
  - python_targets_python3_9
  - python_targets_python3_8
  - python_targets_python3_10
  - python_targets_pypy3
  - ruby_targets_ruby25
  - ruby_targets_ruby24
  - ppc-aix
  - x86-winnt
  - kernel-builtin
  - kernel_Winnt
  - kernel_FreeBSD
  - man
  - minimal
  # Cryptographic library for embedded systems
  - mbedtls
  - modules

  - debug

  # Disable efl/e17
  - ecore

  # Disable redis (hiredis) from unbound
  - redis

  # Disable pptpclient
  - pptp

  # Disable LDAP integration at core level
  - ldap
  - openldap

  - verify-sig

  # Disable gnome-keyring for upper cycles
  - gnome-keyring

  - vim-syntax
  - test
  - test-full
  - savedconfig
  # ATM i disable selinux
  - selinux

  # Disable in GCC
  - objc-gc
  - systemtap
  # Disable in glib
  - fam

  - valadoc
  - cvs
  # Disable brotli support from freetype
  - brotli

  # Disable media stuff
  - allegro
  - devil
  - dumb

  # Disable rados and ceph on core
  - rados
  - ceph
  - cluster

  - heif

  # Disabled for mesa lib
  - vulkan-overlay
  - valgrind

  # Disable fabric stuff
  - ofed
  - rdma
  - ftdi

  - mono
  - libproxy
  - java
  - ruby

  - x86-fbsd
  - x64-macos
  - x64-cygwin
  - amd64-fbsd
  - ppc
  - ppc64

  - userland_BSD

reposcan_disabled_keywords:
  #- ~amd64
  - -*
  - next
