---
defaultGroups:
    - name: users
      must_exist: true
    - name: lp
      must_exist: false
    - name: video
      must_exist: false
    - name: network
      must_exist: false
    - name: storage
      must_exist: false
    - name: wheel
      must_exist: true
    - name: audio
      must_exist: false
    - name: cdrom
      must_exist: false
    - name: cdrw
      must_exist: false
    - name: polkituser
      must_exist: false
    - name: games
      must_exist: false
    - name: scanner
      must_exist: false
    - name: usb
      must_exist: false
    - name: plugdev
      must_exist: false
    - name: messagebus
      must_exist: false
    - name: lpadmin
      must_exist: false

# Avoid that weak password break user setup.
allowWeakPasswords: true
allowWeakPasswordsDefault: true

passwordRequirements:
  minLength: -1
  maxLength: -1

user:
  shell: /bin/bash

doPasswordHashing: false
passwordHashAlgorithm: sha512

autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: true
doReusePassword: true

# Disable flag about using hardened password.
# Until libxcrypt will be updated is better keep
# this to false.
enablePasswordValidation: false

rootConfiguration:
  mode: same
