---
defaultGroups:
    - users
    - lp
    - video
    - network
    - storage
    - wheel
    - audio
    - cdrom
    - cdrw
    - polkituser
    - games
    - scanner
    - usb
    - plugdev
    - messagebus
    - lpadmin

# Avoid that weak password break user setup.
allowWeakPasswords: true

user:
  shell: /bin/bash

autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: true
doReusePassword: true
