requires:
- category: "seed"
  name: "{{ .Values.name }}"
  version: '>=0'
package_dir: /{{ .Values.name }}
steps:
- >-
  qlist -ICSv > /{{ .Values.name }}/usr/share/macaroni/layers/{{ .Values.name }}/pkgslist
