env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
- LUET_PORTAGE_CACHE_PACKAGES=/var/cache/binpkgs
- LUET_PORTAGE_IGNORE_TAR_WARNING=1
- LUET_PORTAGE_PKGMETA=1
- LUET_PORTAGE_PKGFILES=1
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
prelude:
- eval 'rm -rf /pkgdir/ || true' && mkdir -p /pkgdir/{{ .Values.name }} && luet portage
  -- --dir /pkgdir/{{ .Values.name }} {{ ( index .Values.labels "emerge.packages"
  ) }}
- rm -v /var/cache/distfiles/* /var/cache/binpkgs/* || true
package_dir: /pkgdir/{{ .Values.name }}
excludes:
- ^/var/db/pkg/
- ^/var/cache/portage/
- ^/var/git/
requires:
- name: funtoo-office
  version: '>=0'
  category: seed
