env:
- LUET_YES=true
- LUET_NOLOCK=true
- KERNEL_VERSION={{ ( index .Values.labels "kernel.version" ) }}
prelude:
# dev-util/kbuild is needed for virtualbox-guest-additions
- >-
  luet repo update &&
  luet install kernel-5.15/macaroni-sources dev-util/kbuild --nodeps &&
  luet cleanup &&
  cd /usr/src && eval 'rm linux || true' && ln -s linux-$KERNEL_VERSION-macaroni linux
requires:
- category: "seed"
  name: "macaroni-funtoo-base"
  version: ">=0"
