env:
  - JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
  - LUET_PORTAGE_CACHE_PACKAGES="/var/cache/portage/packages"
  - LUET_PORTAGE_IGNORE_TAR_WARNING=1
  - LUET_PORTAGE_PKGMETA=1
  - LUET_PORTAGE_PKGFILES=1
  - FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
prelude:
- eval 'rm -rf /pkgdir/ || true' && mkdir -p /pkgdir/{{ .Values.name }} && luet-portage --dir /pkgdir/{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
- rm -v /var/cache/distfiles/* ${LUET_PORTAGE_CACHE_PACKAGES}/* || true
# Apply macaroni customization
- >-
  sed -i
  -e 's|^DISTRIB_RELEASE.*|DISTRIB_RELEASE={{ ( index .Values.labels "macaroni.version" ) }}|g'
  -e 's|^LSB_VERSION.*|LSB_VERSION="funtoo-macaroni-{{ ( index .Values.labels "macaroni.version" ) }}-amd64"|g'
  lsb-release &&
  cp lsb-release /pkgdir/{{ .Values.name }}/etc/

package_dir: /pkgdir/{{ .Values.name }}
requires:
  - name: funtoo-base
    version: '>=0'
    category: seed
excludes:
  - ^/var/cache/portage/
  - ^/var/git/
