package_dir: /pkgdir/{{ .Values.name | replace "-portage" "" }}
includes:
  - ^/var/db/pkg
  - ^/var/db$
  - ^/var$
requires:
  - name: fontsproto
    version: '{{ .Values.version }}'
    category: x11-proto
