image: "alpine"
prelude:
- >-
  export ANISE_YES=true &&
  export ANISE_NOLOCK=true &&
  export ANISE_VERSION={{ ( index .Values.labels "anise_version" ) }} &&
  apk add wget bash &&
  mkdir /macaroni-terragon &&
  wget https://github.com/macaroni-os/anise/releases/download/v${ANISE_VERSION}/anise-v${ANISE_VERSION}-linux-x86_64 -O /usr/bin/anise &&
  chmod a+x /usr/bin/anise &&
  anise install --force --config ./anise.yaml --sync-repos
  repository/macaroni-terragon-dev
  repository/macaroni-commons
  repository/mark &&
  luet repo update --force --config ./anise.yaml &&
  luet install --force --config ./anise.yaml --skip-finalizers
  app-admin/anise
  system/luet-geaaru
  toolchain/base
  toolchain/meta-repo
  toolchain/meta-geaaru-kit
  virtual/base
  system/entities
  app-admin/whip
  sys-apps/whip-catalog
  app-misc/jq-bin
  macaroni/entities-catalog
  app-misc/yq4-bin
  app-misc/yq3-bin
  dev-util/pkgs-checker &&
  anise cleanup --config ./anise.yaml &&
  mkdir -p /macaroni-terragon/etc/luet &&
  /macaroni-terragon/usr/bin/yq4 e '.system.rootfs = "/"' ./anise.yaml -i &&
  cp ./anise.yaml /macaroni-terragon/etc/anise/ &&
  cd /macaroni-terragon/bin &&
  ln -s bash sh &&
  cd - &&
  touch /macaroni-terragon/etc/passwd &&
  touch /macaroni-terragon/etc/shadow &&
  touch /macaroni-terragon/etc/group &&
  touch /macaroni-terragon/etc/gshadow &&
  /macaroni-terragon/usr/bin/entities merge -s /macaroni-terragon/usr/share/macaroni/entities/ -a
  --users-file /macaroni-terragon/etc/passwd
  --shadow-file /macaroni-terragon/etc/shadow
  --groups-file /macaroni-terragon/etc/group
  --gshadow-file /macaroni-terragon/etc/gshadow &&
  mkdir /layer
# We need to run entities before base image to set users/groups
# and to avoid errors related with user identificationa
package_dir: /layer
