requires:
  - name: "kernel"
    category: "seed-6.1"
    version: ">=0"
env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
package_dir: /{{ .Values.name }}
steps:
- >-
  luet i -y --sync-repos kernel-6.1/macaroni-modules --nodeps &&
  luet i -y sys-apps/kmod bison flex virtual/linux-sources
  yasm virtual/libelf dbus xmlto
  app-text-4.2/docbook-xml-dtd
  app-text-4.4/docbook-xml-dtd
  app-text-3.0/docbook-xml-dtd
  app-text/docbook-xsl-stylesheets
  app-text/build-docbook-catalog
  app-text/sgml-common
  pkgconf iasl
  $(luet s x11-drivers --quiet)
  xrandr xrefresh
  &&
  build-docbook-catalog &&
  luet cleanup &&
  cd /lib/modules/{{ ( index .Values.labels "kernel.version" ) }}-{{ ( index .Values.labels "kernel.suffix" ) }} &&
  ln -s /usr/src/linux-{{ ( index .Values.labels "kernel.version" ) }}-{{ ( index .Values.labels "kernel.suffix" ) }} build
- >-
  epro list &&
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  eval 'rm -rf /{{ .Values.name }} || true' && mkdir /{{ .Values.name }} && \
  luet-portage --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
# It seems that the compression is not handled correct from the ebuild
# I run manually compression for every module
- >-
  for i in /{{ .Values.name }}/lib/modules/{{ ( index .Values.labels "kernel.version" ) }}-macaroni/misc/*.ko ; do
  zstd ${i} -o ${i}.zst --rm ;
  done

excludes:
# Funtoo/Portage stuff
- ^/var/cache/portage/
- ^/var/git/
