image: "macaronios/funtoo-minimal:latest-amd64"
package_dir: /integration
steps:
- mkdir -p /integration/etc/yip.d/live
- cp -rfv yipfiles/* /integration/etc/yip.d/live
- mkdir -p /integration/var/lib/macaroni
- mkdir -p /integration/usr/bin
- cp -rfv live-functions.sh /integration/var/lib/macaroni/
- chmod +x /integration/var/lib/macaroni/live-functions.sh

- cp inittab -v /integration/var/lib/macaroni/

- cp -rfv live.sh /integration/usr/bin/
- chmod +x /integration/usr/bin/live.sh

- cp -rvf entities /integration/var/lib/macaroni/
- cp -rvf entities-macaroni-groups /integration/var/lib/macaroni/

- >-
  eval 'mkdir -p /integration/var/lib/macaroni/X11 || true' &&
  cp -rvf xorg.conf.d /integration/var/lib/macaroni/X11/ &&
  cp -vf xorg.conf /integration/var/lib/macaroni/X11/
- cp -v build-iso-hook.sh /integration/var/lib/macaroni/ &&
  chmod a+x /integration/var/lib/macaroni/build-iso-hook.sh
