requires:
- category: "seed"
  name: "macaroni-funtoo-race4"
  version: ">=0"
env:
- JOBS=3
- PYTHON_TARGETS="python2_7 python3_7"
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox -collision-protect"
prelude:
- >-
  whip hook eclass_db.db_fix_so &&
  whip hook perl.postinst &&
  luet repo update &&
  luet reinstall macaroni/entities-catalog &&
  luet i -y toolchain/calamares &&
  luet cleanup --purge-repos &&
  eselect java-vm set system 1 &&
  mkdir /etc/portage/package.use/ -p &&
  rm -vrf /var/git/meta-repo/kits/python-modules-kit/dev-python/m2r/* &&
  cp -rvf patches/tempita/* /var/git/meta-repo/kits/python-modules-kit/dev-python/tempita/ &&
  cp -rvf package.use/* /etc/portage/package.use/ &&
  emerge -t -j $JOBS dev-python/docutils &&
  emerge -t -j $JOBS dev-python/m2r &&
  emerge -t -j $JOBS {{ ( index .Values.labels "emerge.packages" ) }} &&
  rm -rf /var/cache/portage/distfiles/*
# Force install of docutils to add docutils-compat missing for now on up races
