requires:
- category: "seed"
  name: "funtoo-base"
  version: ">=0"
package_dir: /{{ .Values.name }}
steps:
- >-
  luet repo update &&
  luet upgrade &&
  mkdir -p /{{ .Values.name }}/usr/share/macaroni/layers/{{ .Values.name }}/ &&
  qlist -ICSv > /{{ .Values.name }}/usr/share/macaroni/layers/{{ .Values.name }}/pkgslist &&
  pkgs-checker portage gen-pkgs-uses  --filter-opts /usr/share/pkgs-checker/gen-uses-filter.yaml
  --luet-portage-converter-format
  --treePath atoms/base > /{{ .Values.name }}/usr/share/macaroni/layers/{{ .Values.name }}/portage-converter.yml

